# Generated by Django 5.0.4 on 2024-05-20 13:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_is_processed_order_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Номер телефону має бути у форматі: '0501112233' з +38 на початку за бажанням.", regex='^\\+?3?8?\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='zip_code',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^\\d{5}$', 'Поштовий індекс має містити 5 символів.')]),
        ),
    ]
