name: Python CI

on: 
  push:
    branches:
      - develop

jobs:
  build_and_tests:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      IS_DEVELOPMENT: "True"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - uses: actions/checkout@v3
        if: success() || failure()
      - run: |
          cd tests
          mkdir -p reports
          pytest --html=reports/reports.html
          flake8 --format=html --htmldir=reports/flake_report --extend-ignore=venv,venv.Lib,.github,pycache,.pytest_cache,assets,html --doctests --exclude=.venv,.github,pycache,.pytest_cache,assets,reports.html

      - name: Set output
        if: success() || failure()
        id: results
        run: echo "artifactPath=tests/reports/" >> $GITHUB_OUTPUT

      - uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: test-report
          path: ${{ steps.results.outputs.artifactPath }}


  merge_develop_to_main:
    runs-on: ubuntu-latest
    needs: build_and_tests
  
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{secrets.PAT}}
          fetch-depth: 0
  
      - name: Set up github
        run: |
          git config --global user.name "github_actions"
          git config --global user.email "actions@github.com"
  
      - name: Merge develop branch to main branch
        run: |
          git checkout main
          git merge develop
          git push origin main
